# Generated by Django 2.2.17 on 2020-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jhghjg",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
