# Generated by Django 2.2.17 on 2020-12-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jhghjg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhghjg',
        ),
    ]
